
on: [push, workflow_dispatch]
jobs:
  trigger:
    runs-on: ubuntu-latest
    name: "📦 Trigger Project Test"
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_AUTHOR: ${{ github.author }}
        PAYLOAD_REVISION: "6969"
      with:
        repository: afinoor/heart-disease-prediction
        event: doc_update
        github_pat: ${{ secrets.PAT_TOKEN }}